python learn_policy.py \
--label exp1 \
--ckpt_root ../checkpoints \
--shot_number 2 \
--prompt_format TQ-SA \
--seed 2 \
--model_config /data/qq/Qwen \
--train_number 160 \
--cand_number 10 \
--lr 0.001 \
--epochs 20 \
--embedding_size 128 \
--batch_size 3 \
--gpu 0 \
--gpu_base 1 \
--gpu_embedding 2